<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cities = [
            ["arabic" => "أدوز - بني ملال", "eng" => "Adouz - Beni Mellal", "price" => 40],
            ["arabic" => "أفورار", "eng" => "Afourar", "price" => 40],
            ["arabic" => "أفرا", "eng" => "AFRA", "price" => 40],
            ["arabic" => "أكادير", "eng" => "Agadir", "price" => 40],
            ["arabic" => "أكدز", "eng" => "Agdz", "price" => 40],
            ["arabic" => "أغبالو نكردان", "eng" => "Aghbalou Ncerdan", "price" => 40],
            ["arabic" => "أكلو", "eng" => "Aglou", "price" => 40],
            ["arabic" => "أكوراي", "eng" => "Agourai", "price" => 40],
            ["arabic" => "أكلموس", "eng" => "Aguelmous", "price" => 40],
            ["arabic" => "أحفير", "eng" => "AHFIR", "price" => 40],
            ["arabic" => "عين عيشة", "eng" => "Ain Aicha", "price" => 40],
            ["arabic" => "عين الله", "eng" => "Ain Allah", "price" => 40],
            ["arabic" => "عين عتيق", "eng" => "Ain Attig", "price" => 40],
            ["arabic" => "عين بيضاء - وزان", "eng" => "Ain Beida - Ouazzane", "price" => 40],
            ["arabic" => "عين بني مظهر", "eng" => "Ain Beni Mathar", "price" => 40],
            ["arabic" => "عين بيضاء", "eng" => "Ain Bida", "price" => 40],
            ["arabic" => "عين الشكاك", "eng" => "Ain Cheggag", "price" => 40],
            ["arabic" => "عين الشقف - فاس", "eng" => "Ain Chkef - FES", "price" => 40],
            ["arabic" => "عين دفالي", "eng" => "Ain Defali", "price" => 40],
            ["arabic" => "عين دريج", "eng" => "Ain dorij", "price" => 40],
            ["arabic" => "عين العودة", "eng" => "Ain El Aouda", "price" => 40],
            ["arabic" => "عين الركادة", "eng" => "Ain Erreggada", "price" => 40],
            ["arabic" => "عين حرودة", "eng" => "Ain Harrouda", "price" => 40],
            ["arabic" => "عين جيري - مكناس", "eng" => "Ain jiri - meknes", "price" => 40],
            ["arabic" => "عين قنصرة", "eng" => "Ain Kansara", "price" => 40],
            ["arabic" => "عين كرمة", "eng" => "AIN KARMA", "price" => 40],
            ["arabic" => "عين اللوح", "eng" => "Ain Leuh", "price" => 40],
            ["arabic" => "عين مديونة - تاونات", "eng" => "Ain Mediouna - Taounate", "price" => 40],
            ["arabic" => "عين الركادة", "eng" => "Ain Reggada", "price" => 40],
            ["arabic" => "عين تاوجطات", "eng" => "Ain Taoujdate", "price" => 40],
            ["arabic" => "آيت علي", "eng" => "Ait Ali", "price" => 40],
            ["arabic" => "آيت علي أزرو", "eng" => "Ait Ali Azrou", "price" => 40],
            ["arabic" => "آيت عميرة", "eng" => "Ait Amira", "price" => 40],
            ["arabic" => "آيت باها", "eng" => "Ait Baha", "price" => 40],
            ["arabic" => "آيت بلقاسم", "eng" => "Ait Belkacem", "price" => 40],
            ["arabic" => "آيت إسحاق", "eng" => "Ait Ishaq", "price" => 40],
            ["arabic" => "آيت ملول", "eng" => "Ait melloul", "price" => 40],
            ["arabic" => "آيت ورير", "eng" => "Ait Ourir", "price" => 40],
            ["arabic" => "آيت الربع", "eng" => "Ait Rbaa", "price" => 40],
            ["arabic" => "آيت سعيد", "eng" => "Ait Said", "price" => 40],
            ["arabic" => "آيت يعزم", "eng" => "AIT YAAZEM", "price" => 40],
            ["arabic" => "آيت يوسف", "eng" => "Ait youssef", "price" => 40],
            ["arabic" => "أجدير", "eng" => "Ajdir", "price" => 40],
            ["arabic" => "أقشور", "eng" => "Akchour", "price" => 40],
            ["arabic" => "أخفنير", "eng" => "AKHFNIR", "price" => 40],
            ["arabic" => "أقا", "eng" => "Akka", "price" => 40],
            ["arabic" => "أقا إيغان", "eng" => "Akka Ighane", "price" => 40],
            ["arabic" => "أقليم", "eng" => "Aklim", "price" => 40],
            ["arabic" => "أكنول", "eng" => "Aknoul", "price" => 40],
            ["arabic" => "العروي", "eng" => "Al Aaroui", "price" => 40],
            ["arabic" => "الحسيمة", "eng" => "Al Hoceima", "price" => 40],
            ["arabic" => "الخلفية", "eng" => "Al Khalfia", "price" => 40],
            ["arabic" => "المرابطين", "eng" => "Al Morabitin", "price" => 40],
            ["arabic" => "الماص", "eng" => "Almaz", "price" => 40],
            ["arabic" => "ألنيف", "eng" => "Alnif", "price" => 40],
            ["arabic" => "أمتراس", "eng" => "Ametrass", "price" => 40],
            ["arabic" => "أمزميز", "eng" => "Amizmiz", "price" => 40],
            ["arabic" => "أمسا", "eng" => "Amsa", "price" => 40],
            ["arabic" => "أنزا", "eng" => "Anza", "price" => 40],
            ["arabic" => "أوفوس", "eng" => "Aoufous", "price" => 40],
            ["arabic" => "أولوز", "eng" => "Aoulouz", "price" => 40],
            ["arabic" => "أورير", "eng" => "Aourir", "price" => 40],
            ["arabic" => "أربعاء عونات", "eng" => "Arba Aounate", "price" => 40],
            ["arabic" => "أصيلة", "eng" => "Asilah", "price" => 40],
            ["arabic" => "أسني", "eng" => "Asni", "price" => 40],
            ["arabic" => "آسا", "eng" => "Assa", "price" => 40],
            ["arabic" => "آيت يحيى أو علا", "eng" => "Ayt Yahya Oalla", "price" => 40],
            ["arabic" => "أزمور", "eng" => "Azemmour", "price" => 40],
            ["arabic" => "أزيلال", "eng" => "Azilal", "price" => 40],
            ["arabic" => "أزلا", "eng" => "Azla", "price" => 40],
            ["arabic" => "أزرو", "eng" => "AZROU", "price" => 40],
            ["arabic" => "عزابة - صفرو", "eng" => "Azzaba - Sefrou", "price" => 40],
            ["arabic" => "باب برد", "eng" => "Bab Berred", "price" => 40],
            ["arabic" => "باب مرزوقة", "eng" => "Bab Marzouka", "price" => 40],
            ["arabic" => "باب تازة", "eng" => "Bab Taza", "price" => 40],
            ["arabic" => "باريشينو", "eng" => "Barichino", "price" => 40],
            ["arabic" => "أبي الجعد", "eng" => "Bejaad", "price" => 40],
            ["arabic" => "بلعكيد", "eng" => "Belaaguid", "price" => 40],
            ["arabic" => "بلفاع", "eng" => "Belfaa", "price" => 40],
            ["arabic" => "بليونش", "eng" => "Belyounech", "price" => 40],
            ["arabic" => "بن أحمد", "eng" => "Ben ahmed", "price" => 40],
            ["arabic" => "بن جرير", "eng" => "Ben Guerir", "price" => 40],
            ["arabic" => "بن الطيب", "eng" => "Ben Taieb", "price" => 40],
            ["arabic" => "بن يخلف", "eng" => "Ben Yakhlef", "price" => 40],
            ["arabic" => "بني أحمد - شفشاون", "eng" => "Beni Ahmed - Chefchaouen", "price" => 40],
            ["arabic" => "بني شيكر", "eng" => "Beni Chiker", "price" => 40],
            ["arabic" => "بني درار", "eng" => "Beni Drar", "price" => 40],
            ["arabic" => "بني نصار", "eng" => "Beni Ensar", "price" => 40],
            ["arabic" => "بني ملال", "eng" => "Beni Mellal", "price" => 40],
            ["arabic" => "بني وليد", "eng" => "Beni Oulid", "price" => 40],
            ["arabic" => "بني سيدال الجبل", "eng" => "Beni Sidal Jbel", "price" => 40],
            ["arabic" => "بنسليمان", "eng" => "Benslimane", "price" => 30],
            ["arabic" => "بركان", "eng" => "Berkane", "price" => 40],
            ["arabic" => "برشيد", "eng" => "Berrchid", "price" => 40],
            ["arabic" => "بهاليل", "eng" => "Bhalil", "price" => 40],
            ["arabic" => "بيوكرى", "eng" => "Biougra", "price" => 40],
            ["arabic" => "بئر جديد", "eng" => "Bir Jdid", "price" => 40],
            ["arabic" => "بئر طم طم", "eng" => "Bir Tam Tam", "price" => 40],
            ["arabic" => "بيركوات", "eng" => "Birkouate", "price" => 40],
            ["arabic" => "بيزداد", "eng" => "Bizdad", "price" => 40],
            ["arabic" => "بني عياط", "eng" => "Bni Ayat", "price" => 40],
            ["arabic" => "بني بوعياش", "eng" => "Bni Bouayach", "price" => 40],
            ["arabic" => "بني رزين", "eng" => "Bni Rzine", "price" => 40],
            ["arabic" => "بوعنان تطوان", "eng" => "bouanane tetouan", "price" => 40],
            ["arabic" => "بوعرفة", "eng" => "Bouarfa", "price" => 40],
            ["arabic" => "بوعرك", "eng" => "Bouarg", "price" => 40],
            ["arabic" => "بودربالة", "eng" => "BOUDERBALA", "price" => 40],
            ["arabic" => "بودينار", "eng" => "Boudinar", "price" => 40],
            ["arabic" => "بودنيب", "eng" => "Boudnib", "price" => 40],
            ["arabic" => "بوفكران", "eng" => "Boufakrane", "price" => 40],
            ["arabic" => "بوغريبة", "eng" => "Boughriba", "price" => 40],
            ["arabic" => "بوهودة", "eng" => "Bouhouda", "price" => 40],
            ["arabic" => "بويزكارن", "eng" => "Bouizakarne", "price" => 40],
            ["arabic" => "بوجدور", "eng" => "Boujdour", "price" => 40],
            ["arabic" => "بوجنيبة", "eng" => "Boujniba", "price" => 40],
            ["arabic" => "بولعلام", "eng" => "Boulaalam", "price" => 40],
            ["arabic" => "بولنوار", "eng" => "Boulanouare", "price" => 40],
            ["arabic" => "بولمان", "eng" => "Boulemane", "price" => 40],
            ["arabic" => "بومالن دادس", "eng" => "Boumaln dads", "price" => 40],
            ["arabic" => "بومية", "eng" => "Boumia", "price" => 40],
            ["arabic" => "بونعمان - تيزنيت", "eng" => "Bounaamane - Tiznit", "price" => 40],
            ["arabic" => "بوسكورة", "eng" => "Bouskoura", "price" => 30],
            ["arabic" => "بوزغلال", "eng" => "Bouzaghlal", "price" => 40],
            ["arabic" => "بوزنيقة", "eng" => "Bouznika", "price" => 30],
            ["arabic" => "بريدية", "eng" => "BRIDIA", "price" => 40],
            ["arabic" => "بريكشة", "eng" => "Brikcha", "price" => 40],
            ["arabic" => "كابو نيكرو", "eng" => "Cabo Negro", "price" => 40],
            ["arabic" => "الدار البيضاء", "eng" => "Casablanca", "price" => 20],
            ["arabic" => "شفشاون", "eng" => "Chefchaouen", "price" => 40],
            ["arabic" => "الشلالات", "eng" => "Chellalat", "price" => 30],
            ["arabic" => "شيشاوة", "eng" => "Chichaoua", "price" => 40],
            ["arabic" => "شويتر", "eng" => "Chouiter", "price" => 40],
            ["arabic" => "شريفية", "eng" => "Chrifia", "price" => 40],
            ["arabic" => "الداخلة", "eng" => "Dakhla", "price" => 40],
            ["arabic" => "دالية", "eng" => "Dalia", "price" => 40],
            ["arabic" => "دار 16", "eng" => "Dar 16", "price" => 40],
            ["arabic" => "دار أقوباع", "eng" => "Dar Akoubaa", "price" => 40],
            ["arabic" => "دار بوعزة", "eng" => "Dar Bouazza", "price" => 30],
            ["arabic" => "دار الكبداني", "eng" => "Dar El Kebdani", "price" => 40],
            ["arabic" => "دار ولد زيدوح", "eng" => "Dar Ould Zidouh", "price" => 40],
            ["arabic" => "دردارة", "eng" => "Dardara", "price" => 40],
            ["arabic" => "دشيرة", "eng" => "Dcheira", "price" => 40],
            ["arabic" => "دمنات", "eng" => "Demnate", "price" => 40],
            ["arabic" => "الدروة", "eng" => "Deroua", "price" => 40],
            ["arabic" => "دخيسة", "eng" => "DKHISSA", "price" => 40],
            ["arabic" => "دلالحة", "eng" => "Dlalha", "price" => 40],
            ["arabic" => "دوار بوعزة", "eng" => "Douar Bouazza", "price" => 40],
            ["arabic" => "دوار لعراب", "eng" => "Douar Laareb", "price" => 40],
            ["arabic" => "دوار سيدي موسى", "eng" => "Douar Sidi Moussa", "price" => 40],
            ["arabic" => "دوار سلطان", "eng" => "Douar Soultan", "price" => 40],
            ["arabic" => "دوويات - فاس", "eng" => "Douiyat - FES", "price" => 40],
            ["arabic" => "دراركة", "eng" => "Drarga", "price" => 40],
            ["arabic" => "الدريوش", "eng" => "Driouch", "price" => 40],
            ["arabic" => "الشماعية", "eng" => "Echemmaia", "price" => 40],
            ["arabic" => "العنصر", "eng" => "El aanssar", "price" => 40],
            ["arabic" => "العيون سيدي ملوك", "eng" => "El Aioun Sidi Mellouk", "price" => 40],
            ["arabic" => "العوامرة", "eng" => "El Aouamra", "price" => 40],
            ["arabic" => "العرجات", "eng" => "El Arjate", "price" => 40],
            ["arabic" => "العطاوية", "eng" => "El Attaouia", "price" => 40],
            ["arabic" => "البركة - مكناس", "eng" => "EL BARAKA - MEKNES", "price" => 40],
            ["arabic" => "البرج - خنيفرة", "eng" => "El Borj - Khenifra", "price" => 40],
            ["arabic" => "البروج", "eng" => "El Borouj", "price" => 40],
            ["arabic" => "الكارة", "eng" => "El Gara", "price" => 40],
            ["arabic" => "الحنشان", "eng" => "El Hanchane", "price" => 40],
            ["arabic" => "الحوزية", "eng" => "El Haouzia", "price" => 40],
            ["arabic" => "الحرارتة", "eng" => "El Hrarta", "price" => 40],
            ["arabic" => "الجديدة", "eng" => "El Jadida", "price" => 40],
            ["arabic" => "الجبهة", "eng" => "El Jebeha", "price" => 40],
            ["arabic" => "القباب", "eng" => "El Kebab", "price" => 40],
            ["arabic" => "قلعة السراغنة", "eng" => "El Kelaa des Sraghna", "price" => 40],
            ["arabic" => "الخميس آيت واحي", "eng" => "El Khemis des Aït Ouahi", "price" => 40],
            ["arabic" => "القصيبة - بني ملال", "eng" => "El Ksiba - Beni-Mellal", "price" => 40],
            ["arabic" => "المنصورية", "eng" => "El Mansouria", "price" => 40],
            ["arabic" => "المرسى العيون", "eng" => "EL MARSA LAAYOUNE", "price" => 40],
            ["arabic" => "المنزل - صفرو", "eng" => "El Menzel - SEFROU", "price" => 40],
            ["arabic" => "الوطية طانطان", "eng" => "El Ouatia TAN TAN", "price" => 40],
            ["arabic" => "الحاجب", "eng" => "ELHajeb", "price" => 40],
            ["arabic" => "أرفود", "eng" => "Erfoud", "price" => 40],
            ["arabic" => "الرشيدية", "eng" => "Errachidia", "price" => 40],
            ["arabic" => "الرحمة", "eng" => "Errahma", "price" => 20],
            ["arabic" => "الصويرة", "eng" => "Essaouira", "price" => 40],
            ["arabic" => "السمارة", "eng" => "Essmara SAHARA", "price" => 40],
            ["arabic" => "فج الريح", "eng" => "Faj Errih", "price" => 40],
            ["arabic" => "فم الحصن", "eng" => "Fam El Hisn", "price" => 40],
            ["arabic" => "فرخانة", "eng" => "Farkhana", "price" => 40],
            ["arabic" => "فاس", "eng" => "FES", "price" => 40],
            ["arabic" => "فكيك", "eng" => "Figuig", "price" => 40],
            ["arabic" => "الفنيدق", "eng" => "Fnideq", "price" => 40],
            ["arabic" => "فم العنصر", "eng" => "Foum El Ansar", "price" => 40],
            ["arabic" => "فم اودي - بني ملال", "eng" => "Foum Oudi - Beni Mellal", "price" => 40],
            ["arabic" => "فم زكيد", "eng" => "Foum zguid", "price" => 40],
            ["arabic" => "الفقيه بن صالح", "eng" => "Fquih Ben Salah", "price" => 40],
            ["arabic" => "فريشة - تاونات", "eng" => "Fricha - Taounate", "price" => 40],
            ["arabic" => "كلاز - تاونات", "eng" => "Galaz - Taounate", "price" => 40],
            ["arabic" => "غفساي", "eng" => "Ghafsai", "price" => 40],
            ["arabic" => "غزوة", "eng" => "Ghazoua", "price" => 40],
            ["arabic" => "قواسم", "eng" => "Gouassem", "price" => 40],
            ["arabic" => "كلميمة - الرشيدية", "eng" => "Goulmima - Errachidia", "price" => 40],
            ["arabic" => "كرامة", "eng" => "Gourrama", "price" => 40],
            ["arabic" => "كلميم", "eng" => "Guelmim", "price" => 40],
            ["arabic" => "جرسيف", "eng" => "Guercif", "price" => 40],
            ["arabic" => "كزناية", "eng" => "Gueznaia", "price" => 40],
            ["arabic" => "كيكو", "eng" => "Guigou", "price" => 40],
            ["arabic" => "حد بوموسى - بني ملال", "eng" => "Had Boumoussa - - Beni Mellal", "price" => 40],
            ["arabic" => "حد الدرى", "eng" => "Had Draa", "price" => 40],
            ["arabic" => "حد حرارة - آسفي", "eng" => "Had Hrara- Safi", "price" => 40],
            ["arabic" => "حد السوالم", "eng" => "had soualem", "price" => 30],
            ["arabic" => "حاج قدور", "eng" => "Haj Kaddour", "price" => 40],
            ["arabic" => "هرهورة", "eng" => "Harhoura", "price" => 40],
            ["arabic" => "حطان", "eng" => "Hattane", "price" => 40],
            ["arabic" => "هوارة", "eng" => "Houara", "price" => 40],
            ["arabic" => "حرارة آسفي", "eng" => "Hrara Safi", "price" => 40],
            ["arabic" => "إفران", "eng" => "IFRANE", "price" => 40],
            ["arabic" => "اغرم لعلام", "eng" => "Ighrem Laalam", "price" => 40],
            ["arabic" => "إيمي ودار", "eng" => "Imi Ouaddar", "price" => 40],
            ["arabic" => "إملشيل", "eng" => "Imilchil", "price" => 40],
            ["arabic" => "إمنتانوت", "eng" => "imintanoute", "price" => 40],
            ["arabic" => "إيموزار مرموشة", "eng" => "Imouzzer Marmoucha", "price" => 40],
            ["arabic" => "إيموزار كندر - فاس", "eng" => "Imouzzer-Kandar - FES", "price" => 40],
            ["arabic" => "إمزورن", "eng" => "Imzouren", "price" => 40],
            ["arabic" => "إنشادن", "eng" => "Inchaden", "price" => 40],
            ["arabic" => "إنزكان", "eng" => "Inezgane", "price" => 40],
            ["arabic" => "إساكن", "eng" => "Issaguen", "price" => 40],
            ["arabic" => "جعدار", "eng" => "Jaadar", "price" => 40],
            ["arabic" => "جمعة حودران", "eng" => "Jamaa Houderrane", "price" => 40],
            ["arabic" => "جمعة سحيم", "eng" => "Jamaat shaim", "price" => 40],
            ["arabic" => "جرادة", "eng" => "Jerada", "price" => 40],
            ["arabic" => "جرف الملحة", "eng" => "Jorf El Melha", "price" => 40],
            ["arabic" => "جرف الأصفر", "eng" => "Jorf Lasfar", "price" => 40],
            ["arabic" => "قاع أسراس", "eng" => "kaa asras", "price" => 40],
            ["arabic" => "كابيلا", "eng" => "Kabila", "price" => 40],
            ["arabic" => "كاف نسور", "eng" => "Kaf Nsour", "price" => 40],
            ["arabic" => "قنطرة العسكر", "eng" => "Kantra El Ascar", "price" => 40],
            ["arabic" => "قرية أركمان", "eng" => "Kariat Arekmane", "price" => 40],
            ["arabic" => "قرية با محمد", "eng" => "Kariat Ba Mohamed", "price" => 40],
            ["arabic" => "قصبة تادلة", "eng" => "Kasba Tadla", "price" => 40],
            ["arabic" => "قصبة الطاهر", "eng" => "Kasbah El Taher", "price" => 40],
            ["arabic" => "كاسيطا", "eng" => "Kassita", "price" => 40],
            ["arabic" => "كشولة", "eng" => "Kchoula", "price" => 40],
            ["arabic" => "قلعة مكونة", "eng" => "Kelaat MGouna", "price" => 40],
            ["arabic" => "القنيطرة", "eng" => "Kenitra", "price" => 40],
            ["arabic" => "خميس المضيق", "eng" => "Khamis Mdiq", "price" => 40],
            ["arabic" => "خميس زمامرة", "eng" => "Khemis Zemamera", "price" => 40],
            ["arabic" => "الخميسات", "eng" => "KHEMISSET", "price" => 40],
            ["arabic" => "خنيشات", "eng" => "Khenichet", "price" => 40],
            ["arabic" => "خنيفرة", "eng" => "Khenifra", "price" => 40],
            ["arabic" => "خلالفة", "eng" => "khlalfa", "price" => 40],
            ["arabic" => "خريبكة", "eng" => "Khouribga", "price" => 40],
            ["arabic" => "كريمة", "eng" => "Kraymat", "price" => 40],
            ["arabic" => "القصر الكبير", "eng" => "Ksar El Kebir", "price" => 40],
            ["arabic" => "القصر الصغير", "eng" => "Ksar Sghir", "price" => 40],
            ["arabic" => "المدينة الخضراء", "eng" => "La ville verte", "price" => 40],
            ["arabic" => "العيايطة - بني ملال", "eng" => "Laayayta - Beni Mellal", "price" => 40],
            ["arabic" => "العيون الشرقية", "eng" => "Laayoune Charkia", "price" => 40],
            ["arabic" => "ميناء العيون", "eng" => "laayoune Port", "price" => 40],
            ["arabic" => "العيون الصحراء", "eng" => "Laayoune Sahara", "price" => 40],
            ["arabic" => "الكفيفات", "eng" => "Lagfifat", "price" => 40],
            ["arabic" => "الهراويين", "eng" => "Lahraouyine", "price" => 40],
            ["arabic" => "لهري - خنيفرة", "eng" => "Lahri - khenifra", "price" => 40],
            ["arabic" => "الخيايطة", "eng" => "Lakhyayeta", "price" => 40],
            ["arabic" => "للا ميمونة", "eng" => "Lalla mimouna", "price" => 40],
            ["arabic" => "للا تاكركوست", "eng" => "Lalla Takerkoust", "price" => 40],
            ["arabic" => "لمكانسة - الدار البيضاء", "eng" => "Lamkansa - Casa", "price" => 40],
            ["arabic" => "العرائش", "eng" => "Larache", "price" => 40],
            ["arabic" => "القليعة", "eng" => "Leqliaa", "price" => 40],
            ["arabic" => "الخيايطة - حد السوالم", "eng" => "Lkhyayta - Had soualem", "price" => 40],
            ["arabic" => "لوداية", "eng" => "loudaya", "price" => 40],
            ["arabic" => "لويزية", "eng" => "Louizia", "price" => 40],
            ["arabic" => "الويحة", "eng" => "Lwaiha", "price" => 40],
            ["arabic" => "المضيق", "eng" => "M Diq", "price" => 40],
            ["arabic" => "معازيز", "eng" => "Maaziz", "price" => 40],
            ["arabic" => "مداغ", "eng" => "Madagh", "price" => 40],
            ["arabic" => "مارينا سمير", "eng" => "Marina smir", "price" => 40],
            ["arabic" => "ماريواري", "eng" => "Mariouari", "price" => 40],
            ["arabic" => "مراكش", "eng" => "Marrakech", "price" => 40],
            ["arabic" => "مرتيل", "eng" => "Martil", "price" => 40],
            ["arabic" => "مرزوكة", "eng" => "Marzouga", "price" => 40],
            ["arabic" => "مصمودة", "eng" => "Masmouda", "price" => 40],
            ["arabic" => "ماسة", "eng" => "Massa", "price" => 40],
            ["arabic" => "مشرع بلقصيري", "eng" => "Mechra Bel Ksiri", "price" => 40],
            ["arabic" => "مديونة", "eng" => "Mediouna", "price" => 30],
            ["arabic" => "المهدية", "eng" => "Mehdia", "price" => 40],
            ["arabic" => "مجاط - مراكش", "eng" => "Mejjat - Marrakech", "price" => 40],
            ["arabic" => "مجاط - مكناس", "eng" => "MEJJAT - Meknes", "price" => 40],
            ["arabic" => "ميجي", "eng" => "Mejji", "price" => 40],
            ["arabic" => "مكناس", "eng" => "MEKNES", "price" => 40],
            ["arabic" => "مرنيسة", "eng" => "Mernissa", "price" => 40],
            ["arabic" => "مرس الخير", "eng" => "Mers El Kheir", "price" => 40],
            ["arabic" => "مسكالة", "eng" => "Meskala", "price" => 40],
            ["arabic" => "مهاية - مكناس", "eng" => "MHAYA - MEKNES", "price" => 40],
            ["arabic" => "ميضار", "eng" => "Midar", "price" => 40],
            ["arabic" => "ميدلت", "eng" => "Midelt", "price" => 40],
            ["arabic" => "ميرلفت", "eng" => "Mirleft", "price" => 40],
            ["arabic" => "ميسور", "eng" => "Missour", "price" => 40],
            ["arabic" => "المحمدية", "eng" => "Mohammedia", "price" => 30],
            ["arabic" => "مقريصات", "eng" => "Mokrisset", "price" => 40],
            ["arabic" => "مولاي عبد الله أمغار", "eng" => "Moulay Abellah Amghar", "price" => 40],
            ["arabic" => "مولاي بوعزة", "eng" => "Moulay Bouazza", "price" => 40],
            ["arabic" => "مولاي بوسلهام", "eng" => "Moulay Bousselham", "price" => 40],
            ["arabic" => "مولاي إبراهيم", "eng" => "Moulay Brahim", "price" => 40],
            ["arabic" => "مولاي إدريس زرهون", "eng" => "Moulay Idriss Zerhoun", "price" => 40],
            ["arabic" => "مولاي يعقوب", "eng" => "Moulay Yacoub", "price" => 40],
            ["arabic" => "مقام الطلبة", "eng" => "Mqam Tolba", "price" => 40],
            ["arabic" => "مرامر", "eng" => "Mramer", "price" => 40],
            ["arabic" => "مريرت", "eng" => "Mrirt", "price" => 40],
            ["arabic" => "أمسمرير تنغير", "eng" => "Msemrir tinghir", "price" => 40],
            ["arabic" => "مزودية", "eng" => "Mzoudia", "price" => 40],
            ["arabic" => "الناظور", "eng" => "NADOR", "price" => 40],
            ["arabic" => "النكوب زاكورة", "eng" => "Nkoub Zagora", "price" => 40],
            ["arabic" => "النواصر", "eng" => "Nouaceur", "price" => 30],
            ["arabic" => "نزالة لعضم", "eng" => "Nzalat Laadam", "price" => 40],
            ["arabic" => "واحة سيدي ابراهيم", "eng" => "Ouahat Sidi Brahim", "price" => 40],
            ["arabic" => "الوليدية", "eng" => "Oualidia", "price" => 40],
            ["arabic" => "واويزغت", "eng" => "Ouaouizeght", "price" => 40],
            ["arabic" => "واومانا", "eng" => "Ouaoumana", "price" => 40],
            ["arabic" => "ورزازات", "eng" => "Ouarzazate", "price" => 40],
            ["arabic" => "وزان", "eng" => "Ouazzane", "price" => 40],
            ["arabic" => "الوداية مراكش", "eng" => "OUDAYA Marrakech", "price" => 40],
            ["arabic" => "وادي أمليل", "eng" => "Oued Amlil", "price" => 40],
            ["arabic" => "وادي الجديدة", "eng" => "OUED JDIDA", "price" => 40],
            ["arabic" => "وادي لاو", "eng" => "Oued Laou", "price" => 40],
            ["arabic" => "وادي زم", "eng" => "Oued Zem", "price" => 40],
            ["arabic" => "أوكمس", "eng" => "Ougmas", "price" => 40],
            ["arabic" => "ويدان مراكش", "eng" => "Ouidane MARRAKECH", "price" => 40],
            ["arabic" => "ويسلان", "eng" => "OUISSLAN", "price" => 40],
            ["arabic" => "وجدة", "eng" => "Oujda", "price" => 40],
            ["arabic" => "أولاد علي - بني ملال", "eng" => "Oulad Ali - Beni Mellal", "price" => 40],
            ["arabic" => "أولاد عمران", "eng" => "Oulad Amrane", "price" => 40],
            ["arabic" => "أولاد عياد", "eng" => "Oulad Ayad", "price" => 40],
            ["arabic" => "أولاد برحيل", "eng" => "Oulad Berhil", "price" => 40],
            ["arabic" => "أولاد داحو", "eng" => "Oulad Dahou", "price" => 40],
            ["arabic" => "أولاد فرج", "eng" => "Oulad Frej", "price" => 40],
            ["arabic" => "أولاد غانم", "eng" => "Oulad Ghanem", "price" => 40],
            ["arabic" => "أولاد حسون", "eng" => "OULAD HASSOUN", "price" => 40],
            ["arabic" => "أولاد إسماعيل - بني ملال", "eng" => "Oulad ismail - Beni Mellal", "price" => 40],
            ["arabic" => "أولاد الطيب - فاس", "eng" => "Oulad Tayeb - FES", "price" => 40],
            ["arabic" => "أولاد تايمة", "eng" => "Oulad Teima", "price" => 40],
            ["arabic" => "أولاد يحيى", "eng" => "Oulad yahya", "price" => 40],
            ["arabic" => "أولاد يعيش", "eng" => "Oulad Yaich", "price" => 40],
            ["arabic" => "أولاد يوسف - بني ملال", "eng" => "Oulad Youssef - Beni Mellal", "price" => 40],
            ["arabic" => "أولاد زمام", "eng" => "Oulad zmam", "price" => 40],
            ["arabic" => "أولاد بن رحمون", "eng" => "OULED BEN RAHMOUN", "price" => 40],
            ["arabic" => "أولاد داود - تاونات", "eng" => "Ouled Daoud - Taounate", "price" => 40],
            ["arabic" => "أولاد إدريس - بني ملال", "eng" => "Ouled Driss - Beni Mellal", "price" => 40],
            ["arabic" => "أولاد مبارك", "eng" => "Ouled Mbarek", "price" => 40],
            ["arabic" => "أولاد موسى", "eng" => "Ouled Moussa", "price" => 40],
            ["arabic" => "أولاد مراح", "eng" => "Ouled Mrah", "price" => 40],
            ["arabic" => "أولاد نمة", "eng" => "Ouled Nemma", "price" => 40],
            ["arabic" => "أولاد سعيد الواد", "eng" => "Ouled Said El Oued", "price" => 40],
            ["arabic" => "أولاد ستوت", "eng" => "Ouled Settout", "price" => 40],
            ["arabic" => "أولماس", "eng" => "Oulmes", "price" => 40],
            ["arabic" => "أوناغة", "eng" => "Ounagha", "price" => 40],
            ["arabic" => "أونانة", "eng" => "Ounnana", "price" => 40],
            ["arabic" => "أوريكا", "eng" => "Ourika", "price" => 40],
            ["arabic" => "أورتزاغ - تاونات", "eng" => "Ourtzagh - Taounate", "price" => 40],
            ["arabic" => "أوطاط الحاج", "eng" => "Outat El Haj", "price" => 40],
            ["arabic" => "شاطئ دافيد بوزنيقة", "eng" => "Plage David Bouznika", "price" => 40],
            ["arabic" => "الرباط", "eng" => "RABAT", "price" => 30],
            ["arabic" => "رأس الماء - الناظور", "eng" => "Ras El Ma - Nador", "price" => 40],
            ["arabic" => "رأس الماء - فاس", "eng" => "Ras El Ma-FES", "price" => 40],
            ["arabic" => "رأس تابودة", "eng" => "Ras Tabouda", "price" => 40],
            ["arabic" => "رباط الخير", "eng" => "Ribate El Kheir", "price" => 40],
            ["arabic" => "الريش", "eng" => "Riche", "price" => 40],
            ["arabic" => "الريساني", "eng" => "Rissani", "price" => 40],
            ["arabic" => "الرماني", "eng" => "Rommani", "price" => 40],
            ["arabic" => "السعيدية", "eng" => "SAAIDIA", "price" => 40],
            ["arabic" => "سبع عيون - مكناس", "eng" => "Sabaâ Aïyoun - MEKNES", "price" => 40],
            ["arabic" => "آسفي", "eng" => "Safi", "price" => 40],
            ["arabic" => "سهل بوطاهر - تاونات", "eng" => "Sahel Boutaher - Taounate", "price" => 40],
            ["arabic" => "السعيدية", "eng" => "Saidia", "price" => 40],
            ["arabic" => "سلا الجديدة", "eng" => "Sala Al Jadida", "price" => 30],
            ["arabic" => "سلا", "eng" => "Sale", "price" => 30],
            ["arabic" => "سبت الكردان", "eng" => "Sebt El Guerdane", "price" => 40],
            ["arabic" => "سبت جزولة", "eng" => "Sebt Gzoula", "price" => 40],
            ["arabic" => "سبت متيوة", "eng" => "sebt mtiwa", "price" => 40],
            ["arabic" => "سبت سايس", "eng" => "Sebt Saiss", "price" => 40],
            ["arabic" => "صفرو", "eng" => "Sefrou", "price" => 40],
            ["arabic" => "زغنغن", "eng" => "Segangan", "price" => 40],
            ["arabic" => "سلوان", "eng" => "Selouane", "price" => 40],
            ["arabic" => "صنهاجة - صفرو", "eng" => "Senhaja - Sefrou", "price" => 40],
            ["arabic" => "سطات", "eng" => "Settat", "price" => 40],
            ["arabic" => "سيدي المختار", "eng" => "Sid L Mokhtar", "price" => 40],
            ["arabic" => "سيدي زوين", "eng" => "Sid Zouine", "price" => 40],
            ["arabic" => "سيدي عباد", "eng" => "Sidi Abbad", "price" => 40],
            ["arabic" => "سيدي عبد الله غياث", "eng" => "Sidi Abdellah Ghiat", "price" => 40],
            ["arabic" => "سيدي عبد الرزاق خزازنة", "eng" => "Sidi Abderrazzak Khzazna", "price" => 40],
            ["arabic" => "سيدي عدي", "eng" => "Sidi Addi", "price" => 40],
            ["arabic" => "سيدي عيسى بن علي", "eng" => "Sidi Aissa Ben Ali", "price" => 40],
            ["arabic" => "سيدي علي أزمور", "eng" => "Sidi Ali Azemmour", "price" => 40],
            ["arabic" => "سيدي علال البحراوي", "eng" => "Sidi Allal El Bahraoui", "price" => 40],
            ["arabic" => "سيدي علال التازي", "eng" => "Sidi Allal Tazi", "price" => 40],
            ["arabic" => "سيدي بنور", "eng" => "Sidi Bennour", "price" => 40],
            ["arabic" => "سيدي بيبي", "eng" => "Sidi bibi", "price" => 40],
            ["arabic" => "سيدي بو عثمان", "eng" => "Sidi Bou Othmane", "price" => 40],
            ["arabic" => "سيدي بوخلخال", "eng" => "Sidi Boukhalkhal", "price" => 40],
            ["arabic" => "سيدي بوقنادل", "eng" => "Sidi Bouknadel", "price" => 40],
            ["arabic" => "سيدي بولعلام", "eng" => "Sidi Boulaalam", "price" => 40],
            ["arabic" => "سيدي بوبر", "eng" => "Sidi Bousber", "price" => 40],
            ["arabic" => "سيدي بوزيد الجديدة", "eng" => "Sidi Bouzid El Jadida", "price" => 40],
            ["arabic" => "سيدي بوزيد آسفي", "eng" => "Sidi Bouzid SAFI", "price" => 40],
            ["arabic" => "سيدي حجاج", "eng" => "Sidi Hajjaj", "price" => 40],
            ["arabic" => "سيدي حرازم", "eng" => "Sidi Harazem", "price" => 40],
            ["arabic" => "سيدي إفني", "eng" => "SIDI IFNI", "price" => 40],
            ["arabic" => "سيدي جابر", "eng" => "Sidi Jaber", "price" => 40],
            ["arabic" => "سيدي قاسم", "eng" => "Sidi Kacem", "price" => 40],
            ["arabic" => "سيدي كاوكي", "eng" => "Sidi Kaouki", "price" => 40],
            ["arabic" => "سيدي مسعود", "eng" => "Sidi Massoud", "price" => 40],
            ["arabic" => "سيدي رحال", "eng" => "Sidi Rahal", "price" => 30],
            ["arabic" => "سيدي رضوان", "eng" => "Sidi Redouane", "price" => 40],
            ["arabic" => "سيدي سليمان", "eng" => "Sidi slimane", "price" => 40],
            ["arabic" => "سيدي طيبي", "eng" => "Sidi Taibi", "price" => 40],
            ["arabic" => "سيدي يحيى الغرب", "eng" => "Sidi Yahya El Gharb", "price" => 40],
            ["arabic" => "سيدي يحيى زعير", "eng" => "Sidi Yahya Zaer", "price" => 40],
            ["arabic" => "سخينات", "eng" => "Skhinate", "price" => 40],
            ["arabic" => "الصخيرات", "eng" => "Skhirat", "price" => 30],
            ["arabic" => "صخور الرحامنة", "eng" => "Skhour Rehamna", "price" => 40],
            ["arabic" => "السمارة", "eng" => "Smara", "price" => 40],
            ["arabic" => "سميمو", "eng" => "Smimou", "price" => 40],
            ["arabic" => "سويحلة", "eng" => "Souihla", "price" => 40],
            ["arabic" => "سوق الكور", "eng" => "SOUK EL GOUR", "price" => 40],
            ["arabic" => "سوق الأحد برادية", "eng" => "Souk El Had Des Bradia", "price" => 40],
            ["arabic" => "سوق خميس الساحل", "eng" => "Souk Khemis du Sahel", "price" => 40],
            ["arabic" => "سوق الأربعاء", "eng" => "SOUK LARBAA", "price" => 40],
            ["arabic" => "سوق السبت أولاد نمة", "eng" => "Souk Sebt Oulad Nemma", "price" => 40],
            ["arabic" => "سوق اثنين مكن", "eng" => "Souk Tnine Moghane", "price" => 40],
            ["arabic" => "إسليحات", "eng" => "Stehat", "price" => 40],
            ["arabic" => "تاشرافت", "eng" => "Tachrafat", "price" => 40],
            ["arabic" => "تدارت - أكادير", "eng" => "Taddart - Agadir", "price" => 40],
            ["arabic" => "تدارت - تازة", "eng" => "Taddart - Taza", "price" => 40],
            ["arabic" => "تفرسيت", "eng" => "Tafersit", "price" => 40],
            ["arabic" => "تفتشت", "eng" => "Tafetachte", "price" => 40],
            ["arabic" => "تفوغالت", "eng" => "Tafoughalt", "price" => 40],
            ["arabic" => "تافراوت", "eng" => "Tafraoute", "price" => 40],
            ["arabic" => "تغازوت", "eng" => "Taghazout", "price" => 40],
            ["arabic" => "تاكونيت زاكورة", "eng" => "Tagounite zagora", "price" => 40],
            ["arabic" => "تاكزيرت", "eng" => "Tagzert", "price" => 40],
            ["arabic" => "تحناوت", "eng" => "Tahannaout", "price" => 40],
            ["arabic" => "تاهلة", "eng" => "TAHLA", "price" => 40],
            ["arabic" => "تاليوين", "eng" => "Taliouine", "price" => 40],
            ["arabic" => "تلمست", "eng" => "Talmest", "price" => 40],
            ["arabic" => "تمنار", "eng" => "Tamanar", "price" => 40],
            ["arabic" => "تامنصورت", "eng" => "Tamansourt", "price" => 40],
            ["arabic" => "تاماريس", "eng" => "Tamaris", "price" => 40],
            ["arabic" => "تملالت", "eng" => "Tamellalt", "price" => 40],
            ["arabic" => "تامصلوحت", "eng" => "Tameslohte", "price" => 40],
            ["arabic" => "تامسنا", "eng" => "Tamesna", "price" => 40],
            ["arabic" => "تمراغت", "eng" => "Tamraght", "price" => 40],
            ["arabic" => "تمسمان", "eng" => "Tamsamane", "price" => 40],
            ["arabic" => "تامزموت", "eng" => "Tamzmout", "price" => 40],
            ["arabic" => "تانديت", "eng" => "Tandit", "price" => 40],
            ["arabic" => "طنجة", "eng" => "Tanger", "price" => 40],
            ["arabic" => "تنوغة", "eng" => "Tanougha", "price" => 40],
            ["arabic" => "طانطان", "eng" => "TANTAN", "price" => 40],
            ["arabic" => "تاونات", "eng" => "Taounate", "price" => 40],
            ["arabic" => "تاوريرت", "eng" => "Taourirt", "price" => 40],
            ["arabic" => "طرفاية", "eng" => "Tarfaya", "price" => 40],
            ["arabic" => "تاركيست", "eng" => "Targuist", "price" => 40],
            ["arabic" => "تارودانت", "eng" => "Taroudant", "price" => 40],
            ["arabic" => "تراست", "eng" => "Tarrast", "price" => 40],
            ["arabic" => "تاسلطانت", "eng" => "Tassoultante", "price" => 40],
            ["arabic" => "طاطا", "eng" => "TATA", "price" => 40],
            ["arabic" => "تازة", "eng" => "TAZA", "price" => 40],
            ["arabic" => "تازارين", "eng" => "Tazarine", "price" => 40],
            ["arabic" => "تازيناخت", "eng" => "Tazenakht", "price" => 40],
            ["arabic" => "تازناخت", "eng" => "Taznakht", "price" => 40],
            ["arabic" => "ثلاث أزلاف", "eng" => "Telat Azlaf", "price" => 40],
            ["arabic" => "تمارة", "eng" => "Temara", "price" => 30],
            ["arabic" => "تمسية", "eng" => "Temsia", "price" => 40],
            ["arabic" => "تندارة", "eng" => "Tendrara", "price" => 40],
            ["arabic" => "تروال - وزان", "eng" => "Teroual - Ouazzane", "price" => 40],
            ["arabic" => "تطوان", "eng" => "Tetouan", "price" => 40],
            ["arabic" => "ظهر السوق", "eng" => "Thar Es-Souk", "price" => 40],
            ["arabic" => "تيداس", "eng" => "Tiddas", "price" => 40],
            ["arabic" => "تيدزي", "eng" => "Tidzi", "price" => 40],
            ["arabic" => "تيفلت", "eng" => "TIFLET", "price" => 40],
            ["arabic" => "تيغسالين", "eng" => "Tighssaline", "price" => 40],
            ["arabic" => "تيكوين", "eng" => "Tikiouine", "price" => 40],
            ["arabic" => "تمحضيت", "eng" => "Timahdite", "price" => 40],
            ["arabic" => "تيموليلت", "eng" => "Timoulilte", "price" => 40],
            ["arabic" => "تين منصور", "eng" => "Tin Mansour", "price" => 40],
            ["arabic" => "تنجداد", "eng" => "Tinejdad", "price" => 40],
            ["arabic" => "تنغير", "eng" => "Tinghir", "price" => 40],
            ["arabic" => "تيسة", "eng" => "Tissa", "price" => 40],
            ["arabic" => "تسينت", "eng" => "Tissint", "price" => 40],
            ["arabic" => "تيت مليل", "eng" => "Tit Mellil", "price" => 40],
            ["arabic" => "تيزي وسلي", "eng" => "Tizi Ouasli", "price" => 40],
            ["arabic" => "تيزنيت", "eng" => "Tiznit", "price" => 40],
            ["arabic" => "تيزتوتين", "eng" => "Tiztoutine", "price" => 40],
            ["arabic" => "اثنين شتوكة الجديدة", "eng" => "Tnine Chtouka El jadida", "price" => 40],
            ["arabic" => "اثنين الغربية", "eng" => "Tnine Gharbia", "price" => 40],
            ["arabic" => "اليوسفية", "eng" => "Youssoufia", "price" => 40],
            ["arabic" => "الزاك", "eng" => "Zag", "price" => 40],
            ["arabic" => "زاكورة", "eng" => "Zagora", "price" => 40],
            ["arabic" => "زايدة", "eng" => "Zaida", "price" => 40],
            ["arabic" => "زايو", "eng" => "Zaio", "price" => 40],
            ["arabic" => "زاوية بوكرين - صفرو", "eng" => "Zaouiat Bougrine - Sefrou", "price" => 40],
            ["arabic" => "زاوية الشيخ", "eng" => "Zaouiat Cheikh", "price" => 40],
            ["arabic" => "زاوية سيدي إسماعيل", "eng" => "Zaouit Sidi Smail", "price" => 40],
            ["arabic" => "زغنغن", "eng" => "Zeghanghane", "price" => 40],
            ["arabic" => "زناتة", "eng" => "Zenata", "price" => 40],
            ["arabic" => "زومي", "eng" => "Zoumi", "price" => 40],
            ["arabic" => "زريزر", "eng" => "Zrizer", "price" => 40],
        ];

        \App\Models\City::truncate();

        foreach ($cities as $city) {
            \App\Models\City::create([
                'name' => $city['eng'],
                'arabic_name' => $city['arabic'],
                'price' => $city['price'],
            ]);
        }
    }
}
