<?php

return [
    "default_price" => 35,
    "cities" => [
        ["name_ar" => "آسا", "name_en" => "Assa", "price" => 40],
        ["name_ar" => "آسفي", "name_en" => "Safi", "price" => 40],
        ["name_ar" => "آيت إسحاق", "name_en" => "Ait Ishaq", "price" => 40],
        ["name_ar" => "آيت الربع", "name_en" => "Ait Rbaa", "price" => 40],
        ["name_ar" => "آيت باها", "name_en" => "Ait Baha", "price" => 40],
        ["name_ar" => "آيت بلقاسم", "name_en" => "Ait Belkacem", "price" => 40],
        ["name_ar" => "آيت سعيد", "name_en" => "Ait Said", "price" => 40],
        ["name_ar" => "آيت علي", "name_en" => "Ait Ali", "price" => 40],
        ["name_ar" => "آيت علي أزرو", "name_en" => "Ait Ali Azrou", "price" => 40],
        ["name_ar" => "آيت عميرة", "name_en" => "Ait Amira", "price" => 40],
        ["name_ar" => "آيت ملول", "name_en" => "Ait melloul", "price" => 40],
        ["name_ar" => "آيت ورير", "name_en" => "Ait Ourir", "price" => 40],
        ["name_ar" => "آيت يحيى أو علا", "name_en" => "Ayt Yahya Oalla", "price" => 40],
        ["name_ar" => "آيت يعزم", "name_en" => "AIT YAAZEM", "price" => 40],
        ["name_ar" => "آيت يوسف", "name_en" => "Ait youssef", "price" => 40],
        ["name_ar" => "أبي الجعد", "name_en" => "Bejaad", "price" => 40],
        ["name_ar" => "أجدير", "name_en" => "Ajdir", "price" => 40],
        ["name_ar" => "أحفير", "name_en" => "AHFIR", "price" => 40],
        ["name_ar" => "أخفنير", "name_en" => "AKHFNIR", "price" => 40],
        ["name_ar" => "أدوز - بني ملال", "name_en" => "Adouz - Beni Mellal", "price" => 40],
        ["name_ar" => "أربعاء عونات", "name_en" => "Arba Aounate", "price" => 40],
        ["name_ar" => "أرفود", "name_en" => "Erfoud", "price" => 40],
        ["name_ar" => "أزرو", "name_en" => "AZROU", "price" => 40],
        ["name_ar" => "أزلا", "name_en" => "Azla", "price" => 40],
        ["name_ar" => "أزمور", "name_en" => "Azemmour", "price" => 40],
        ["name_ar" => "أزيلال", "name_en" => "Azilal", "price" => 40],
        ["name_ar" => "أسني", "name_en" => "Asni", "price" => 40],
        ["name_ar" => "أصيلة", "name_en" => "Asilah", "price" => 40],
        ["name_ar" => "أغبالو نكردان", "name_en" => "Aghbalou Ncerdan", "price" => 40],
        ["name_ar" => "أفرا", "name_en" => "AFRA", "price" => 40],
        ["name_ar" => "أفورار", "name_en" => "Afourar", "price" => 40],
        ["name_ar" => "أقا", "name_en" => "Akka", "price" => 40],
        ["name_ar" => "أقا إيغان", "name_en" => "Akka Ighane", "price" => 40],
        ["name_ar" => "أقشور", "name_en" => "Akchour", "price" => 40],
        ["name_ar" => "أقليم", "name_en" => "Aklim", "price" => 40],
        ["name_ar" => "أكادير", "name_en" => "Agadir", "price" => 40],
        ["name_ar" => "أكدز", "name_en" => "Agdz", "price" => 40],
        ["name_ar" => "أكلموس", "name_en" => "Aguelmous", "price" => 40],
        ["name_ar" => "أكلو", "name_en" => "Aglou", "price" => 40],
        ["name_ar" => "أكنول", "name_en" => "Aknoul", "price" => 40],
        ["name_ar" => "أكوراي", "name_en" => "Agourai", "price" => 40],
        ["name_ar" => "ألنيف", "name_en" => "Alnif", "price" => 40],
        ["name_ar" => "أمتراس", "name_en" => "Ametrass", "price" => 40],
        ["name_ar" => "أمزميز", "name_en" => "Amizmiz", "price" => 40],
        ["name_ar" => "أمسا", "name_en" => "Amsa", "price" => 40],
        ["name_ar" => "أمسمرير تنغير", "name_en" => "Msemrir tinghir", "price" => 40],
        ["name_ar" => "أنزا", "name_en" => "Anza", "price" => 40],
        ["name_ar" => "أورتزاغ - تاونات", "name_en" => "Ourtzagh - Taounate", "price" => 40],
        ["name_ar" => "أورير", "name_en" => "Aourir", "price" => 40],
        ["name_ar" => "أوريكا", "name_en" => "Ourika", "price" => 40],
        ["name_ar" => "أوطاط الحاج", "name_en" => "Outat El Haj", "price" => 40],
        ["name_ar" => "أوفوس", "name_en" => "Aoufous", "price" => 40],
        ["name_ar" => "أوكمس", "name_en" => "Ougmas", "price" => 40],
        ["name_ar" => "أولاد إدريس - بني ملال", "name_en" => "Ouled Driss - Beni Mellal", "price" => 40],
        ["name_ar" => "أولاد إسماعيل - بني ملال", "name_en" => "Oulad ismail - Beni Mellal", "price" => 40],
        ["name_ar" => "أولاد الطيب - فاس", "name_en" => "Oulad Tayeb - FES", "price" => 40],
        ["name_ar" => "أولاد برحيل", "name_en" => "Oulad Berhil", "price" => 40],
        ["name_ar" => "أولاد بن رحمون", "name_en" => "OULED BEN RAHMOUN", "price" => 40],
        ["name_ar" => "أولاد تايمة", "name_en" => "Oulad Teima", "price" => 40],
        ["name_ar" => "أولاد حسون", "name_en" => "OULAD HASSOUN", "price" => 40],
        ["name_ar" => "أولاد داحو", "name_en" => "Oulad Dahou", "price" => 40],
        ["name_ar" => "أولاد داود - تاونات", "name_en" => "Ouled Daoud - Taounate", "price" => 40],
        ["name_ar" => "أولاد زمام", "name_en" => "Oulad zmam", "price" => 40],
        ["name_ar" => "أولاد ستوت", "name_en" => "Ouled Settout", "price" => 40],
        ["name_ar" => "أولاد سعيد الواد", "name_en" => "Ouled Said El Oued", "price" => 40],
        ["name_ar" => "أولاد علي - بني ملال", "name_en" => "Oulad Ali - Beni Mellal", "price" => 40],
        ["name_ar" => "أولاد عمران", "name_en" => "Oulad Amrane", "price" => 40],
        ["name_ar" => "أولاد عياد", "name_en" => "Oulad Ayad", "price" => 40],
        ["name_ar" => "أولاد غانم", "name_en" => "Oulad Ghanem", "price" => 40],
        ["name_ar" => "أولاد فرج", "name_en" => "Oulad Frej", "price" => 40],
        ["name_ar" => "أولاد مبارك", "name_en" => "Ouled Mbarek", "price" => 40],
        ["name_ar" => "أولاد مراح", "name_en" => "Ouled Mrah", "price" => 40],
        ["name_ar" => "أولاد موسى", "name_en" => "Ouled Moussa", "price" => 40],
        ["name_ar" => "أولاد نمة", "name_en" => "Ouled Nemma", "price" => 40],
        ["name_ar" => "أولاد يحيى", "name_en" => "Oulad yahya", "price" => 40],
        ["name_ar" => "أولاد يعيش", "name_en" => "Oulad Yaich", "price" => 40],
        ["name_ar" => "أولاد يوسف - بني ملال", "name_en" => "Oulad Youssef - Beni Mellal", "price" => 40],
        ["name_ar" => "أولماس", "name_en" => "Oulmes", "price" => 40],
        ["name_ar" => "أولوز", "name_en" => "Aoulouz", "price" => 40],
        ["name_ar" => "أوناغة", "name_en" => "Ounagha", "price" => 40],
        ["name_ar" => "أونانة", "name_en" => "Ounnana", "price" => 40],
        ["name_ar" => "إساكن", "name_en" => "Issaguen", "price" => 40],
        ["name_ar" => "إسليحات", "name_en" => "Stehat", "price" => 40],
        ["name_ar" => "إفران", "name_en" => "IFRANE", "price" => 40],
        ["name_ar" => "إمزورن", "name_en" => "Imzouren", "price" => 40],
        ["name_ar" => "إملشيل", "name_en" => "Imilchil", "price" => 40],
        ["name_ar" => "إمنتانوت", "name_en" => "imintanoute", "price" => 40],
        ["name_ar" => "إنزكان", "name_en" => "Inezgane", "price" => 40],
        ["name_ar" => "إنشادن", "name_en" => "Inchaden", "price" => 40],
        ["name_ar" => "إيموزار كندر - فاس", "name_en" => "Imouzzer-Kandar - FES", "price" => 40],
        ["name_ar" => "إيموزار مرموشة", "name_en" => "Imouzzer Marmoucha", "price" => 40],
        ["name_ar" => "إيمي ودار", "name_en" => "Imi Ouaddar", "price" => 40],
        ["name_ar" => "اثنين الغربية", "name_en" => "Tnine Gharbia", "price" => 40],
        ["name_ar" => "اثنين شتوكة الجديدة", "name_en" => "Tnine Chtouka El jadida", "price" => 40],
        ["name_ar" => "اغرم لعلام", "name_en" => "Ighrem Laalam", "price" => 40],
        ["name_ar" => "البرج - خنيفرة", "name_en" => "El Borj - Khenifra", "price" => 40],
        ["name_ar" => "البركة - مكناس", "name_en" => "EL BARAKA - MEKNES", "price" => 40],
        ["name_ar" => "البروج", "name_en" => "El Borouj", "price" => 40],
        ["name_ar" => "الجبهة", "name_en" => "El Jebeha", "price" => 40],
        ["name_ar" => "الجديدة", "name_en" => "El Jadida", "price" => 40],
        ["name_ar" => "الحاجب", "name_en" => "ELHajeb", "price" => 40],
        ["name_ar" => "الحرارتة", "name_en" => "El Hrarta", "price" => 40],
        ["name_ar" => "الحسيمة", "name_en" => "Al Hoceima", "price" => 40],
        ["name_ar" => "الحنشان", "name_en" => "El Hanchane", "price" => 40],
        ["name_ar" => "الحوزية", "name_en" => "El Haouzia", "price" => 40],
        ["name_ar" => "الخلفية", "name_en" => "Al Khalfia", "price" => 40],
        ["name_ar" => "الخميس آيت واحي", "name_en" => "El Khemis des Aït Ouahi", "price" => 40],
        ["name_ar" => "الخميسات", "name_en" => "KHEMISSET", "price" => 40],
        ["name_ar" => "الخيايطة", "name_en" => "Lakhyayeta", "price" => 40],
        ["name_ar" => "الخيايطة - حد السوالم", "name_en" => "Lkhyayta - Had soualem", "price" => 40],
        ["name_ar" => "الداخلة", "name_en" => "Dakhla", "price" => 40],
        ["name_ar" => "الدار البيضاء", "name_en" => "Casablanca", "price" => 20],
        ["name_ar" => "الدروة", "name_en" => "Deroua", "price" => 40],
        ["name_ar" => "الدريوش", "name_en" => "Driouch", "price" => 40],
        ["name_ar" => "الرباط", "name_en" => "RABAT", "price" => 30],
        ["name_ar" => "الرحمة", "name_en" => "Errahma", "price" => 20],
        ["name_ar" => "الرشيدية", "name_en" => "Errachidia", "price" => 40],
        ["name_ar" => "الرماني", "name_en" => "Rommani", "price" => 40],
        ["name_ar" => "الريساني", "name_en" => "Rissani", "price" => 40],
        ["name_ar" => "الريش", "name_en" => "Riche", "price" => 40],
        ["name_ar" => "الزاك", "name_en" => "Zag", "price" => 40],
        ["name_ar" => "السعيدية", "name_en" => "SAAIDIA", "price" => 40],
        ["name_ar" => "السمارة", "name_en" => "Smara", "price" => 40],
        ["name_ar" => "الشلالات", "name_en" => "Chellalat", "price" => 30],
        ["name_ar" => "الشماعية", "name_en" => "Echemmaia", "price" => 40],
        ["name_ar" => "الصخيرات", "name_en" => "Skhirat", "price" => 30],
        ["name_ar" => "الصويرة", "name_en" => "Essaouira", "price" => 40],
        ["name_ar" => "العرائش", "name_en" => "Larache", "price" => 40],
        ["name_ar" => "العرجات", "name_en" => "El Arjate", "price" => 40],
        ["name_ar" => "العروي", "name_en" => "Al Aaroui", "price" => 40],
        ["name_ar" => "العطاوية", "name_en" => "El Attaouia", "price" => 40],
        ["name_ar" => "العنصر", "name_en" => "El aanssar", "price" => 40],
        ["name_ar" => "العوامرة", "name_en" => "El Aouamra", "price" => 40],
        ["name_ar" => "العيايطة - بني ملال", "name_en" => "Laayayta - Beni Mellal", "price" => 40],
        ["name_ar" => "العيون الشرقية", "name_en" => "Laayoune Charkia", "price" => 40],
        ["name_ar" => "العيون الصحراء", "name_en" => "Laayoune Sahara", "price" => 40],
        ["name_ar" => "العيون سيدي ملوك", "name_en" => "El Aioun Sidi Mellouk", "price" => 40],
        ["name_ar" => "الفقيه بن صالح", "name_en" => "Fquih Ben Salah", "price" => 40],
        ["name_ar" => "الفنيدق", "name_en" => "Fnideq", "price" => 40],
        ["name_ar" => "القباب", "name_en" => "El Kebab", "price" => 40],
        ["name_ar" => "القصر الصغير", "name_en" => "Ksar Sghir", "price" => 40],
        ["name_ar" => "القصر الكبير", "name_en" => "Ksar El Kebir", "price" => 40],
        ["name_ar" => "القصيبة - بني ملال", "name_en" => "El Ksiba - Beni-Mellal", "price" => 40],
        ["name_ar" => "القليعة", "name_en" => "Leqliaa", "price" => 40],
        ["name_ar" => "القنيطرة", "name_en" => "Kenitra", "price" => 40],
        ["name_ar" => "الكارة", "name_en" => "El Gara", "price" => 40],
        ["name_ar" => "الكفيفات", "name_en" => "Lagfifat", "price" => 40],
        ["name_ar" => "الماص", "name_en" => "Almaz", "price" => 40],
        ["name_ar" => "المحمدية", "name_en" => "Mohammedia", "price" => 30],
        ["name_ar" => "المدينة الخضراء", "name_en" => "La ville verte", "price" => 40],
        ["name_ar" => "المرابطين", "name_en" => "Al Morabitin", "price" => 40],
        ["name_ar" => "المرسى العيون", "name_en" => "EL MARSA LAAYOUNE", "price" => 40],
        ["name_ar" => "المضيق", "name_en" => "M Diq", "price" => 40],
        ["name_ar" => "المنزل - صفرو", "name_en" => "El Menzel - SEFROU", "price" => 40],
        ["name_ar" => "المنصورية", "name_en" => "El Mansouria", "price" => 40],
        ["name_ar" => "المهدية", "name_en" => "Mehdia", "price" => 40],
        ["name_ar" => "الناظور", "name_en" => "NADOR", "price" => 40],
        ["name_ar" => "النكوب زاكورة", "name_en" => "Nkoub Zagora", "price" => 40],
        ["name_ar" => "النواصر", "name_en" => "Nouaceur", "price" => 30],
        ["name_ar" => "الهراويين", "name_en" => "Lahraouyine", "price" => 40],
        ["name_ar" => "الوداية مراكش", "name_en" => "OUDAYA Marrakech", "price" => 40],
        ["name_ar" => "الوطية طانطان", "name_en" => "El Ouatia TAN TAN", "price" => 40],
        ["name_ar" => "الوليدية", "name_en" => "Oualidia", "price" => 40],
        ["name_ar" => "الويحة", "name_en" => "Lwaiha", "price" => 40],
        ["name_ar" => "اليوسفية", "name_en" => "Youssoufia", "price" => 40],
        ["name_ar" => "بئر جديد", "name_en" => "Bir Jdid", "price" => 40],
        ["name_ar" => "بئر طم طم", "name_en" => "Bir Tam Tam", "price" => 40],
        ["name_ar" => "باب برد", "name_en" => "Bab Berred", "price" => 40],
        ["name_ar" => "باب تازة", "name_en" => "Bab Taza", "price" => 40],
        ["name_ar" => "باب مرزوقة", "name_en" => "Bab Marzouka", "price" => 40],
        ["name_ar" => "باريشينو", "name_en" => "Barichino", "price" => 40],
        ["name_ar" => "برشيد", "name_en" => "Berrchid", "price" => 40],
        ["name_ar" => "بركان", "name_en" => "Berkane", "price" => 40],
        ["name_ar" => "بريدية", "name_en" => "BRIDIA", "price" => 40],
        ["name_ar" => "بريكشة", "name_en" => "Brikcha", "price" => 40],
        ["name_ar" => "بلعكيد", "name_en" => "Belaaguid", "price" => 40],
        ["name_ar" => "بلفاع", "name_en" => "Belfaa", "price" => 40],
        ["name_ar" => "بليونش", "name_en" => "Belyounech", "price" => 40],
        ["name_ar" => "بن أحمد", "name_en" => "Ben ahmed", "price" => 40],
        ["name_ar" => "بن الطيب", "name_en" => "Ben Taieb", "price" => 40],
        ["name_ar" => "بن جرير", "name_en" => "Ben Guerir", "price" => 40],
        ["name_ar" => "بن يخلف", "name_en" => "Ben Yakhlef", "price" => 40],
        ["name_ar" => "بنسليمان", "name_en" => "Benslimane", "price" => 30],
        ["name_ar" => "بني أحمد - شفشاون", "name_en" => "Beni Ahmed - Chefchaouen", "price" => 40],
        ["name_ar" => "بني بوعياش", "name_en" => "Bni Bouayach", "price" => 40],
        ["name_ar" => "بني درار", "name_en" => "Beni Drar", "price" => 40],
        ["name_ar" => "بني رزين", "name_en" => "Bni Rzine", "price" => 40],
        ["name_ar" => "بني سيدال الجبل", "name_en" => "Beni Sidal Jbel", "price" => 40],
        ["name_ar" => "بني شيكر", "name_en" => "Beni Chiker", "price" => 40],
        ["name_ar" => "بني عياط", "name_en" => "Bni Ayat", "price" => 40],
        ["name_ar" => "بني ملال", "name_en" => "Beni Mellal", "price" => 40],
        ["name_ar" => "بني نصار", "name_en" => "Beni Ensar", "price" => 40],
        ["name_ar" => "بني وليد", "name_en" => "Beni Oulid", "price" => 40],
        ["name_ar" => "بهاليل", "name_en" => "Bhalil", "price" => 40],
        ["name_ar" => "بوجدور", "name_en" => "Boujdour", "price" => 40],
        ["name_ar" => "بوجنيبة", "name_en" => "Boujniba", "price" => 40],
        ["name_ar" => "بودربالة", "name_en" => "BOUDERBALA", "price" => 40],
        ["name_ar" => "بودنيب", "name_en" => "Boudnib", "price" => 40],
        ["name_ar" => "بودينار", "name_en" => "Boudinar", "price" => 40],
        ["name_ar" => "بوزغلال", "name_en" => "Bouzaghlal", "price" => 40],
        ["name_ar" => "بوزنيقة", "name_en" => "Bouznika", "price" => 30],
        ["name_ar" => "بوسكورة", "name_en" => "Bouskoura", "price" => 30],
        ["name_ar" => "بوعرفة", "name_en" => "Bouarfa", "price" => 40],
        ["name_ar" => "بوعرك", "name_en" => "Bouarg", "price" => 40],
        ["name_ar" => "بوعنان تطوان", "name_en" => "bouanane tetouan", "price" => 40],
        ["name_ar" => "بوغريبة", "name_en" => "Boughriba", "price" => 40],
        ["name_ar" => "بوفكران", "name_en" => "Boufakrane", "price" => 40],
        ["name_ar" => "بولعلام", "name_en" => "Boulaalam", "price" => 40],
        ["name_ar" => "بولمان", "name_en" => "Boulemane", "price" => 40],
        ["name_ar" => "بولنوار", "name_en" => "Boulanouare", "price" => 40],
        ["name_ar" => "بومالن دادس", "name_en" => "Boumaln dads", "price" => 40],
        ["name_ar" => "بومية", "name_en" => "Boumia", "price" => 40],
        ["name_ar" => "بونعمان - تيزنيت", "name_en" => "Bounaamane - Tiznit", "price" => 40],
        ["name_ar" => "بوهودة", "name_en" => "Bouhouda", "price" => 40],
        ["name_ar" => "بويزكارن", "name_en" => "Bouizakarne", "price" => 40],
        ["name_ar" => "بيركوات", "name_en" => "Birkouate", "price" => 40],
        ["name_ar" => "بيزداد", "name_en" => "Bizdad", "price" => 40],
        ["name_ar" => "بيوكرى", "name_en" => "Biougra", "price" => 40],
        ["name_ar" => "تاركيست", "name_en" => "Targuist", "price" => 40],
        ["name_ar" => "تارودانت", "name_en" => "Taroudant", "price" => 40],
        ["name_ar" => "تازارين", "name_en" => "Tazarine", "price" => 40],
        ["name_ar" => "تازة", "name_en" => "TAZA", "price" => 40],
        ["name_ar" => "تازناخت", "name_en" => "Taznakht", "price" => 40],
        ["name_ar" => "تازيناخت", "name_en" => "Tazenakht", "price" => 40],
        ["name_ar" => "تاسلطانت", "name_en" => "Tassoultante", "price" => 40],
        ["name_ar" => "تاشرافت", "name_en" => "Tachrafat", "price" => 40],
        ["name_ar" => "تافراوت", "name_en" => "Tafraoute", "price" => 40],
        ["name_ar" => "تاكزيرت", "name_en" => "Tagzert", "price" => 40],
        ["name_ar" => "تاكونيت زاكورة", "name_en" => "Tagounite zagora", "price" => 40],
        ["name_ar" => "تاليوين", "name_en" => "Taliouine", "price" => 40],
        ["name_ar" => "تاماريس", "name_en" => "Tamaris", "price" => 40],
        ["name_ar" => "تامزموت", "name_en" => "Tamzmout", "price" => 40],
        ["name_ar" => "تامسنا", "name_en" => "Tamesna", "price" => 40],
        ["name_ar" => "تامصلوحت", "name_en" => "Tameslohte", "price" => 40],
        ["name_ar" => "تامنصورت", "name_en" => "Tamansourt", "price" => 40],
        ["name_ar" => "تانديت", "name_en" => "Tandit", "price" => 40],
        ["name_ar" => "تاهلة", "name_en" => "TAHLA", "price" => 40],
        ["name_ar" => "تاوريرت", "name_en" => "Taourirt", "price" => 40],
        ["name_ar" => "تاونات", "name_en" => "Taounate", "price" => 40],
        ["name_ar" => "تحناوت", "name_en" => "Tahannaout", "price" => 40],
        ["name_ar" => "تدارت - أكادير", "name_en" => "Taddart - Agadir", "price" => 40],
        ["name_ar" => "تدارت - تازة", "name_en" => "Taddart - Taza", "price" => 40],
        ["name_ar" => "تراست", "name_en" => "Tarrast", "price" => 40],
        ["name_ar" => "تروال - وزان", "name_en" => "Teroual - Ouazzane", "price" => 40],
        ["name_ar" => "تسينت", "name_en" => "Tissint", "price" => 40],
        ["name_ar" => "تطوان", "name_en" => "Tetouan", "price" => 40],
        ["name_ar" => "تغازوت", "name_en" => "Taghazout", "price" => 40],
        ["name_ar" => "تفتشت", "name_en" => "Tafetachte", "price" => 40],
        ["name_ar" => "تفرسيت", "name_en" => "Tafersit", "price" => 40],
        ["name_ar" => "تفوغالت", "name_en" => "Tafoughalt", "price" => 40],
        ["name_ar" => "تلمست", "name_en" => "Talmest", "price" => 40],
        ["name_ar" => "تمارة", "name_en" => "Temara", "price" => 30],
        ["name_ar" => "تمحضيت", "name_en" => "Timahdite", "price" => 40],
        ["name_ar" => "تمراغت", "name_en" => "Tamraght", "price" => 40],
        ["name_ar" => "تمسمان", "name_en" => "Tamsamane", "price" => 40],
        ["name_ar" => "تمسية", "name_en" => "Temsia", "price" => 40],
        ["name_ar" => "تملالت", "name_en" => "Tamellalt", "price" => 40],
        ["name_ar" => "تمنار", "name_en" => "Tamanar", "price" => 40],
        ["name_ar" => "تنجداد", "name_en" => "Tinejdad", "price" => 40],
        ["name_ar" => "تندارة", "name_en" => "Tendrara", "price" => 40],
        ["name_ar" => "تنغير", "name_en" => "Tinghir", "price" => 40],
        ["name_ar" => "تنوغة", "name_en" => "Tanougha", "price" => 40],
        ["name_ar" => "تيت مليل", "name_en" => "Tit Mellil", "price" => 40],
        ["name_ar" => "تيداس", "name_en" => "Tiddas", "price" => 40],
        ["name_ar" => "تيدزي", "name_en" => "Tidzi", "price" => 40],
        ["name_ar" => "تيزتوتين", "name_en" => "Tiztoutine", "price" => 40],
        ["name_ar" => "تيزنيت", "name_en" => "Tiznit", "price" => 40],
        ["name_ar" => "تيزي وسلي", "name_en" => "Tizi Ouasli", "price" => 40],
        ["name_ar" => "تيسة", "name_en" => "Tissa", "price" => 40],
        ["name_ar" => "تيغسالين", "name_en" => "Tighssaline", "price" => 40],
        ["name_ar" => "تيفلت", "name_en" => "TIFLET", "price" => 40],
        ["name_ar" => "تيكوين", "name_en" => "Tikiouine", "price" => 40],
        ["name_ar" => "تيموليلت", "name_en" => "Timoulilte", "price" => 40],
        ["name_ar" => "تين منصور", "name_en" => "Tin Mansour", "price" => 40],
        ["name_ar" => "ثلاث أزلاف", "name_en" => "Telat Azlaf", "price" => 40],
        ["name_ar" => "جرادة", "name_en" => "Jerada", "price" => 40],
        ["name_ar" => "جرسيف", "name_en" => "Guercif", "price" => 40],
        ["name_ar" => "جرف الأصفر", "name_en" => "Jorf Lasfar", "price" => 40],
        ["name_ar" => "جرف الملحة", "name_en" => "Jorf El Melha", "price" => 40],
        ["name_ar" => "جعدار", "name_en" => "Jaadar", "price" => 40],
        ["name_ar" => "جمعة حودران", "name_en" => "Jamaa Houderrane", "price" => 40],
        ["name_ar" => "جمعة سحيم", "name_en" => "Jamaat shaim", "price" => 40],
        ["name_ar" => "حاج قدور", "name_en" => "Haj Kaddour", "price" => 40],
        ["name_ar" => "حد الدرى", "name_en" => "Had Draa", "price" => 40],
        ["name_ar" => "حد السوالم", "name_en" => "had soualem", "price" => 30],
        ["name_ar" => "حد بوموسى - بني ملال", "name_en" => "Had Boumoussa - - Beni Mellal", "price" => 40],
        ["name_ar" => "حد حرارة - آسفي", "name_en" => "Had Hrara- Safi", "price" => 40],
        ["name_ar" => "حرارة آسفي", "name_en" => "Hrara Safi", "price" => 40],
        ["name_ar" => "حطان", "name_en" => "Hattane", "price" => 40],
        ["name_ar" => "خريبكة", "name_en" => "Khouribga", "price" => 40],
        ["name_ar" => "خلالفة", "name_en" => "khlalfa", "price" => 40],
        ["name_ar" => "خميس المضيق", "name_en" => "Khamis Mdiq", "price" => 40],
        ["name_ar" => "خميس زمامرة", "name_en" => "Khemis Zemamera", "price" => 40],
        ["name_ar" => "خنيشات", "name_en" => "Khenichet", "price" => 40],
        ["name_ar" => "خنيفرة", "name_en" => "Khenifra", "price" => 40],
        ["name_ar" => "دار 16", "name_en" => "Dar 16", "price" => 40],
        ["name_ar" => "دار أقوباع", "name_en" => "Dar Akoubaa", "price" => 40],
        ["name_ar" => "دار الكبداني", "name_en" => "Dar El Kebdani", "price" => 40],
        ["name_ar" => "دار الكداري", "name_en" => "Dar Gueddari", "price" => 40],
        ["name_ar" => "دار بوعزة", "name_en" => "Dar Bouazza", "price" => 30],
        ["name_ar" => "دار ولد زيدوح", "name_en" => "Dar Ould Zidouh", "price" => 40],
        ["name_ar" => "دالية", "name_en" => "Dalia", "price" => 40],
        ["name_ar" => "دخيسة", "name_en" => "DKHISSA", "price" => 40],
        ["name_ar" => "دراركة", "name_en" => "Drarga", "price" => 40],
        ["name_ar" => "دردارة", "name_en" => "Dardara", "price" => 40],
        ["name_ar" => "دشيرة", "name_en" => "Dcheira", "price" => 40],
        ["name_ar" => "دلالحة", "name_en" => "Dlalha", "price" => 40],
        ["name_ar" => "دمنات", "name_en" => "Demnate", "price" => 40],
        ["name_ar" => "دوار بوعزة", "name_en" => "Douar Bouazza", "price" => 40],
        ["name_ar" => "دوار سلطان", "name_en" => "Douar Soultan", "price" => 40],
        ["name_ar" => "دوار سيدي موسى", "name_en" => "Douar Sidi Moussa", "price" => 40],
        ["name_ar" => "دوار لعراب", "name_en" => "Douar Laareb", "price" => 40],
        ["name_ar" => "دوويات - فاس", "name_en" => "Douiyat - FES", "price" => 40],
        ["name_ar" => "رأس الماء - الناظور", "name_en" => "Ras El Ma - Nador", "price" => 40],
        ["name_ar" => "رأس الماء - فاس", "name_en" => "Ras El Ma-FES", "price" => 40],
        ["name_ar" => "رأس تابودة", "name_en" => "Ras Tabouda", "price" => 40],
        ["name_ar" => "رباط الخير", "name_en" => "Ribate El Kheir", "price" => 40],
        ["name_ar" => "زاكورة", "name_en" => "Zagora", "price" => 40],
        ["name_ar" => "زاوية الشيخ", "name_en" => "Zaouiat Cheikh", "price" => 40],
        ["name_ar" => "زاوية بوكرين - صفرو", "name_en" => "Zaouiat Bougrine - Sefrou", "price" => 40],
        ["name_ar" => "زاوية سيدي إسماعيل", "name_en" => "Zaouit Sidi Smail", "price" => 40],
        ["name_ar" => "زايدة", "name_en" => "Zaida", "price" => 40],
        ["name_ar" => "زايو", "name_en" => "Zaio", "price" => 40],
        ["name_ar" => "زريزر", "name_en" => "Zrizer", "price" => 40],
        ["name_ar" => "زغنغن", "name_en" => "Segangan", "price" => 40],
        ["name_ar" => "زناتة", "name_en" => "Zenata", "price" => 40],
        ["name_ar" => "زومي", "name_en" => "Zoumi", "price" => 40],
        ["name_ar" => "سبت الكردان", "name_en" => "Sebt El Guerdane", "price" => 40],
        ["name_ar" => "سبت جزولة", "name_en" => "Sebt Gzoula", "price" => 40],
        ["name_ar" => "سبت سايس", "name_en" => "Sebt Saiss", "price" => 40],
        ["name_ar" => "سبت متيوة", "name_en" => "sebt mtiwa", "price" => 40],
        ["name_ar" => "سبع عيون - مكناس", "name_en" => "Sabaâ Aïyoun - MEKNES", "price" => 40],
        ["name_ar" => "سخينات", "name_en" => "Skhinate", "price" => 40],
        ["name_ar" => "سطات", "name_en" => "Settat", "price" => 40],
        ["name_ar" => "سلا", "name_en" => "Sale", "price" => 30],
        ["name_ar" => "سلا الجديدة", "name_en" => "Sala Al Jadida", "price" => 30],
        ["name_ar" => "سلوان", "name_en" => "Selouane", "price" => 40],
        ["name_ar" => "سميمو", "name_en" => "Smimou", "price" => 40],
        ["name_ar" => "سهل بوطاهر - تاونات", "name_en" => "Sahel Boutaher - Taounate", "price" => 40],
        ["name_ar" => "سوق اثنين مكن", "name_en" => "Souk Tnine Moghane", "price" => 40],
        ["name_ar" => "سوق الأحد برادية", "name_en" => "Souk El Had Des Bradia", "price" => 40],
        ["name_ar" => "سوق الأربعاء", "name_en" => "SOUK LARBAA", "price" => 40],
        ["name_ar" => "سوق السبت أولاد نمة", "name_en" => "Souk Sebt Oulad Nemma", "price" => 40],
        ["name_ar" => "سوق الكور", "name_en" => "SOUK EL GOUR", "price" => 40],
        ["name_ar" => "سوق خميس الساحل", "name_en" => "Souk Khemis du Sahel", "price" => 40],
        ["name_ar" => "سويحلة", "name_en" => "Souihla", "price" => 40],
        ["name_ar" => "سيدي إفني", "name_en" => "SIDI IFNI", "price" => 40],
        ["name_ar" => "سيدي المختار", "name_en" => "Sid L Mokhtar", "price" => 40],
        ["name_ar" => "سيدي بنور", "name_en" => "Sidi Bennour", "price" => 40],
        ["name_ar" => "سيدي بو عثمان", "name_en" => "Sidi Bou Othmane", "price" => 40],
        ["name_ar" => "سيدي بوبر", "name_en" => "Sidi Bousber", "price" => 40],
        ["name_ar" => "سيدي بوخلخال", "name_en" => "Sidi Boukhalkhal", "price" => 40],
        ["name_ar" => "سيدي بوزيد آسفي", "name_en" => "Sidi Bouzid SAFI", "price" => 40],
        ["name_ar" => "سيدي بوزيد الجديدة", "name_en" => "Sidi Bouzid El Jadida", "price" => 40],
        ["name_ar" => "سيدي بوقنادل", "name_en" => "Sidi Bouknadel", "price" => 40],
        ["name_ar" => "سيدي بولعلام", "name_en" => "Sidi Boulaalam", "price" => 40],
        ["name_ar" => "سيدي بيبي", "name_en" => "Sidi bibi", "price" => 40],
        ["name_ar" => "سيدي جابر", "name_en" => "Sidi Jaber", "price" => 40],
        ["name_ar" => "سيدي حجاج", "name_en" => "Sidi Hajjaj", "price" => 40],
        ["name_ar" => "سيدي حرازم", "name_en" => "Sidi Harazem", "price" => 40],
        ["name_ar" => "سيدي رحال", "name_en" => "Sidi Rahal", "price" => 30],
        ["name_ar" => "سيدي رضوان", "name_en" => "Sidi Redouane", "price" => 40],
        ["name_ar" => "سيدي زوين", "name_en" => "Sid Zouine", "price" => 40],
        ["name_ar" => "سيدي سليمان", "name_en" => "Sidi slimane", "price" => 40],
        ["name_ar" => "سيدي طيبي", "name_en" => "Sidi Taibi", "price" => 40],
        ["name_ar" => "سيدي عباد", "name_en" => "Sidi Abbad", "price" => 40],
        ["name_ar" => "سيدي عبد الرزاق خزازنة", "name_en" => "Sidi Abderrazzak Khzazna", "price" => 40],
        ["name_ar" => "سيدي عبد الله غياث", "name_en" => "Sidi Abdellah Ghiat", "price" => 40],
        ["name_ar" => "سيدي عدي", "name_en" => "Sidi Addi", "price" => 40],
        ["name_ar" => "سيدي علال البحراوي", "name_en" => "Sidi Allal El Bahraoui", "price" => 40],
        ["name_ar" => "سيدي علال التازي", "name_en" => "Sidi Allal Tazi", "price" => 40],
        ["name_ar" => "سيدي علي أزمور", "name_en" => "Sidi Ali Azemmour", "price" => 40],
        ["name_ar" => "سيدي عيسى بن علي", "name_en" => "Sidi Aissa Ben Ali", "price" => 40],
        ["name_ar" => "سيدي قاسم", "name_en" => "Sidi Kacem", "price" => 40],
        ["name_ar" => "سيدي كاوكي", "name_en" => "Sidi Kaouki", "price" => 40],
        ["name_ar" => "سيدي مسعود", "name_en" => "Sidi Massoud", "price" => 40],
        ["name_ar" => "سيدي يحيى الغرب", "name_en" => "Sidi Yahya El Gharb", "price" => 40],
        ["name_ar" => "سيدي يحيى زعير", "name_en" => "Sidi Yahya Zaer", "price" => 40],
        ["name_ar" => "شاطئ دافيد بوزنيقة", "name_en" => "Plage David Bouznika", "price" => 40],
        ["name_ar" => "شريفية", "name_en" => "Chrifia", "price" => 40],
        ["name_ar" => "شفشاون", "name_en" => "Chefchaouen", "price" => 40],
        ["name_ar" => "شويتر", "name_en" => "Chouiter", "price" => 40],
        ["name_ar" => "شيشاوة", "name_en" => "Chichaoua", "price" => 40],
        ["name_ar" => "صخور الرحامنة", "name_en" => "Skhour Rehamna", "price" => 40],
        ["name_ar" => "صفرو", "name_en" => "Sefrou", "price" => 40],
        ["name_ar" => "صنهاجة - صفرو", "name_en" => "Senhaja - Sefrou", "price" => 40],
        ["name_ar" => "طاطا", "name_en" => "TATA", "price" => 40],
        ["name_ar" => "طانطان", "name_en" => "TANTAN", "price" => 40],
        ["name_ar" => "طرفاية", "name_en" => "Tarfaya", "price" => 40],
        ["name_ar" => "طنجة", "name_en" => "Tanger", "price" => 40],
        ["name_ar" => "ظهر السوق", "name_en" => "Thar Es-Souk", "price" => 40],
        ["name_ar" => "عزابة - صفرو", "name_en" => "Azzaba - Sefrou", "price" => 40],
        ["name_ar" => "عين الركادة", "name_en" => "Ain Erreggada", "price" => 40],
        ["name_ar" => "عين الشقف - فاس", "name_en" => "Ain Chkef - FES", "price" => 40],
        ["name_ar" => "عين الشكاك", "name_en" => "Ain Cheggag", "price" => 40],
        ["name_ar" => "عين العودة", "name_en" => "Ain El Aouda", "price" => 40],
        ["name_ar" => "عين الله", "name_en" => "Ain Allah", "price" => 40],
        ["name_ar" => "عين اللوح", "name_en" => "Ain Leuh", "price" => 40],
        ["name_ar" => "عين بني مظهر", "name_en" => "Ain Beni Mathar", "price" => 40],
        ["name_ar" => "عين بيضاء", "name_en" => "Ain Bida", "price" => 40],
        ["name_ar" => "عين بيضاء - وزان", "name_en" => "Ain Beida - Ouazzane", "price" => 40],
        ["name_ar" => "عين تاوجطات", "name_en" => "Ain Taoujdate", "price" => 40],
        ["name_ar" => "عين جيري - مكناس", "name_en" => "Ain jiri - meknes", "price" => 40],
        ["name_ar" => "عين حرودة", "name_en" => "Ain Harrouda", "price" => 40],
        ["name_ar" => "عين دريج", "name_en" => "Ain dorij", "price" => 40],
        ["name_ar" => "عين دفالي", "name_en" => "Ain Defali", "price" => 40],
        ["name_ar" => "عين عتيق", "name_en" => "Ain Attig", "price" => 40],
        ["name_ar" => "عين عيشة", "name_en" => "Ain Aicha", "price" => 40],
        ["name_ar" => "عين قنصرة", "name_en" => "Ain Kansara", "price" => 40],
        ["name_ar" => "عين كرمة", "name_en" => "AIN KARMA", "price" => 40],
        ["name_ar" => "عين مديونة - تاونات", "name_en" => "Ain Mediouna - Taounate", "price" => 40],
        ["name_ar" => "غزوة", "name_en" => "Ghazoua", "price" => 40],
        ["name_ar" => "غفساي", "name_en" => "Ghafsai", "price" => 40],
        ["name_ar" => "فاس", "name_en" => "FES", "price" => 40],
        ["name_ar" => "فج الريح", "name_en" => "Faj Errih", "price" => 40],
        ["name_ar" => "فرخانة", "name_en" => "Farkhana", "price" => 40],
        ["name_ar" => "فريشة - تاونات", "name_en" => "Fricha - Taounate", "price" => 40],
        ["name_ar" => "فكيك", "name_en" => "Figuig", "price" => 40],
        ["name_ar" => "فم الحصن", "name_en" => "Fam El Hisn", "price" => 40],
        ["name_ar" => "فم العنصر", "name_en" => "Foum El Ansar", "price" => 40],
        ["name_ar" => "فم اودي - بني ملال", "name_en" => "Foum Oudi - Beni Mellal", "price" => 40],
        ["name_ar" => "فم زكيد", "name_en" => "Foum zguid", "price" => 40],
        ["name_ar" => "قاع أسراس", "name_en" => "kaa asras", "price" => 40],
        ["name_ar" => "قرية أركمان", "name_en" => "Kariat Arekmane", "price" => 40],
        ["name_ar" => "قرية با محمد", "name_en" => "Kariat Ba Mohamed", "price" => 40],
        ["name_ar" => "قصبة الطاهر", "name_en" => "Kasbah El Taher", "price" => 40],
        ["name_ar" => "قصبة تادلة", "name_en" => "Kasba Tadla", "price" => 40],
        ["name_ar" => "قلعة السراغنة", "name_en" => "El Kelaa des Sraghna", "price" => 40],
        ["name_ar" => "قلعة مكونة", "name_en" => "Kelaat MGouna", "price" => 40],
        ["name_ar" => "قنطرة العسكر", "name_en" => "Kantra El Ascar", "price" => 40],
        ["name_ar" => "قواسم", "name_en" => "Gouassem", "price" => 40],
        ["name_ar" => "كابو نيكرو", "name_en" => "Cabo Negro", "price" => 40],
        ["name_ar" => "كابيلا", "name_en" => "Kabila", "price" => 40],
        ["name_ar" => "كاسيطا", "name_en" => "Kassita", "price" => 40],
        ["name_ar" => "كاف نسور", "name_en" => "Kaf Nsour", "price" => 40],
        ["name_ar" => "كرامة", "name_en" => "Gourrama", "price" => 40],
        ["name_ar" => "كريمة", "name_en" => "Kraymat", "price" => 40],
        ["name_ar" => "كزناية", "name_en" => "Gueznaia", "price" => 40],
        ["name_ar" => "كشولة", "name_en" => "Kchoula", "price" => 40],
        ["name_ar" => "كلاز - تاونات", "name_en" => "Galaz - Taounate", "price" => 40],
        ["name_ar" => "كلميم", "name_en" => "Guelmim", "price" => 40],
        ["name_ar" => "كلميمة - الرشيدية", "name_en" => "Goulmima - Errachidia", "price" => 40],
        ["name_ar" => "كيكو", "name_en" => "Guigou", "price" => 40],
        ["name_ar" => "للا تاكركوست", "name_en" => "Lalla Takerkoust", "price" => 40],
        ["name_ar" => "للا ميمونة", "name_en" => "Lalla mimouna", "price" => 40],
        ["name_ar" => "لهري - خنيفرة", "name_en" => "Lahri - khenifra", "price" => 40],
        ["name_ar" => "لوداية", "name_en" => "loudaya", "price" => 40],
        ["name_ar" => "لويزية", "name_en" => "Louizia", "price" => 40],
        ["name_ar" => "مارينا سمير", "name_en" => "Marina smir", "price" => 40],
        ["name_ar" => "ماريواري", "name_en" => "Mariouari", "price" => 40],
        ["name_ar" => "ماسة", "name_en" => "Massa", "price" => 40],
        ["name_ar" => "مجاط - مراكش", "name_en" => "Mejjat - Marrakech", "price" => 40],
        ["name_ar" => "مجاط - مكناس", "name_en" => "MEJJAT - Meknes", "price" => 40],
        ["name_ar" => "مداغ", "name_en" => "Madagh", "price" => 40],
        ["name_ar" => "مديونة", "name_en" => "Mediouna", "price" => 30],
        ["name_ar" => "مراكش", "name_en" => "Marrakech", "price" => 40],
        ["name_ar" => "مرامر", "name_en" => "Mramer", "price" => 40],
        ["name_ar" => "مرتيل", "name_en" => "Martil", "price" => 40],
        ["name_ar" => "مرزوكة", "name_en" => "Marzouga", "price" => 40],
        ["name_ar" => "مرس الخير", "name_en" => "Mers El Kheir", "price" => 40],
        ["name_ar" => "مرنيسة", "name_en" => "Mernissa", "price" => 40],
        ["name_ar" => "مريرت", "name_en" => "Mrirt", "price" => 40],
        ["name_ar" => "مزودية", "name_en" => "Mzoudia", "price" => 40],
        ["name_ar" => "مسكالة", "name_en" => "Meskala", "price" => 40],
        ["name_ar" => "مشرع بلقصيري", "name_en" => "Mechra Bel Ksiri", "price" => 40],
        ["name_ar" => "مصمودة", "name_en" => "Masmouda", "price" => 40],
        ["name_ar" => "معازيز", "name_en" => "Maaziz", "price" => 40],
        ["name_ar" => "مقام الطلبة", "name_en" => "Mqam Tolba", "price" => 40],
        ["name_ar" => "مقريصات", "name_en" => "Mokrisset", "price" => 40],
        ["name_ar" => "مكناس", "name_en" => "MEKNES", "price" => 40],
        ["name_ar" => "مهاية - مكناس", "name_en" => "MHAYA - MEKNES", "price" => 40],
        ["name_ar" => "مولاي إبراهيم", "name_en" => "Moulay Brahim", "price" => 40],
        ["name_ar" => "مولاي إدريس زرهون", "name_en" => "Moulay Idriss Zerhoun", "price" => 40],
        ["name_ar" => "مولاي بوسلهام", "name_en" => "Moulay Bousselham", "price" => 40],
        ["name_ar" => "مولاي بوعزة", "name_en" => "Moulay Bouazza", "price" => 40],
        ["name_ar" => "مولاي عبد الله أمغار", "name_en" => "Moulay Abellah Amghar", "price" => 40],
        ["name_ar" => "مولاي يعقوب", "name_en" => "Moulay Yacoub", "price" => 40],
        ["name_ar" => "ميجي", "name_en" => "Mejji", "price" => 40],
        ["name_ar" => "ميدلت", "name_en" => "Midelt", "price" => 40],
        ["name_ar" => "ميرلفت", "name_en" => "Mirleft", "price" => 40],
        ["name_ar" => "ميسور", "name_en" => "Missour", "price" => 40],
        ["name_ar" => "ميضار", "name_en" => "Midar", "price" => 40],
        ["name_ar" => "ميناء العيون", "name_en" => "laayoune Port", "price" => 40],
        ["name_ar" => "نزالة لعضم", "name_en" => "Nzalat Laadam", "price" => 40],
        ["name_ar" => "هرهورة", "name_en" => "Harhoura", "price" => 40],
        ["name_ar" => "هوارة", "name_en" => "Houara", "price" => 40],
        ["name_ar" => "واحة سيدي ابراهيم", "name_en" => "Ouahat Sidi Brahim", "price" => 40],
        ["name_ar" => "وادي أمليل", "name_en" => "Oued Amlil", "price" => 40],
        ["name_ar" => "وادي الجديدة", "name_en" => "OUED JDIDA", "price" => 40],
        ["name_ar" => "وادي زم", "name_en" => "Oued Zem", "price" => 40],
        ["name_ar" => "وادي لاو", "name_en" => "Oued Laou", "price" => 40],
        ["name_ar" => "واومانا", "name_en" => "Ouaoumana", "price" => 40],
        ["name_ar" => "واويزغت", "name_en" => "Ouaouizeght", "price" => 40],
        ["name_ar" => "وجدة", "name_en" => "Oujda", "price" => 40],
        ["name_ar" => "ورزازات", "name_en" => "Ouarzazate", "price" => 40],
        ["name_ar" => "وزان", "name_en" => "Ouazzane", "price" => 40],
        ["name_ar" => "ويدان مراكش", "name_en" => "Ouidane MARRAKECH", "price" => 40],
        ["name_ar" => "ويسلان", "name_en" => "OUISSLAN", "price" => 40],
    ],
];
